### ISSUE TITLE
Max file size

### ISSUE THREAD

**Issue by gabrielkoerich** [OGPoyraz/tinymce-aws-s3-upload-plugin#1]
Hi! Nice plugin.

Can I limit the max file size for uploads?

**Comment by OGPoyraz** [comment]
Sorry for late answer,
Plugin doesn't have option to limit max file sizes but you can do it on your s3 bucket. 
Btw this I don't recommend to use this plugin on public environments. It makes your secret keys reachable so it may be risky.
Have a great day!
