### ISSUE TITLE
successCallback not fired

### ISSUE THREAD

**Issue by areknow** [OGPoyraz/tinymce-aws-s3-upload-plugin#3]
Thanks a lot for this great plugin!

Ive integrated it with my current project, and have succeeded in uploading an image to my bucket from the editor. 

Once the progress bar finishes, nothing else happens for me. No callback is fired. Nothing is inserted into the editor. I added a console log inside of successCallback but it appears its not being called.

Any idea how I can move forward with this?

Thanks

**Comment by OGPoyraz** [comment]
Hello @areknow,

Sorry for late answer. Did you tried to insert image to editor in successCallback ?

```javascript
successCallback: (editor, url) => {  // optional
  // For example
  switch (url.split('.').pop()) {
    case 'png':
    case 'jpg':
    case 'jpeg': {
      editor.execCommand('mceInsertContent', false, `<img src="${url}" style="display: block;margin: 0 auto;text-align: center; max-width:100%;" />`);
      break;
    }
    default: {
      editor.execCommand('mceInsertContent', false, `<a href="${url}">${url}</a>`);
    }
  }
}```

Or can you see any error ?
